/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICampaign,
  ICampaignInterface,
} from "../../../contracts/interfaces/ICampaign";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_campaignId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_nftId",
        type: "uint256",
      },
    ],
    name: "addNftToCampaign",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        internalType: "string",
        name: "_description",
        type: "string",
      },
      {
        internalType: "string",
        name: "_baseURI",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_timeStart",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_timeEnd",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_expireClaim",
        type: "uint256",
      },
    ],
    name: "createCampaign",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllCampaign",
    outputs: [
      {
        internalType: "uint256[]",
        name: "id",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "period",
        type: "string",
      },
    ],
    name: "getCampaignByPeriod",
    outputs: [
      {
        internalType: "uint256[]",
        name: "id",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_campaignId",
        type: "uint256",
      },
    ],
    name: "getCampaignInfo",
    outputs: [
      {
        components: [
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "description",
            type: "string",
          },
          {
            internalType: "string",
            name: "baseURI",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "timeStart",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "timeEnd",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "expireClaim",
            type: "uint256",
          },
          {
            internalType: "uint256[]",
            name: "nftId",
            type: "uint256[]",
          },
        ],
        internalType: "struct ICampaign.campaignsInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_timeStart",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_timeEnd",
        type: "uint256",
      },
    ],
    name: "hasCampaignRunning",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_campaignId",
        type: "uint256",
      },
    ],
    name: "isRunningCampaign",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICampaign__factory {
  static readonly abi = _abi;
  static createInterface(): ICampaignInterface {
    return new Interface(_abi) as ICampaignInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICampaign {
    return new Contract(address, _abi, runner) as unknown as ICampaign;
  }
}
