/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICampaign } from "./ICampaign";
export type { ICryptoCoffMember } from "./ICryptoCoffMember";
export type { ICryptoCoffPoint } from "./ICryptoCoffPoint";
export type { ILogAutomation } from "./ILogAutomation";
