import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/providers/theme-provider";
import WagmiProvider from "@/providers/wagmi-provider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <WagmiProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {/* <Navbar /> */}
            {children}
            {/* <Footer />
            <DialogLayout />
            <DrawerLayout /> */}
            <Toaster />
          </ThemeProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
