import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import DialogLayout from "@/components/layout/components/DialogLayout";
import DrawerLayout from "@/components/layout/components/DrawerLayout";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/providers/theme-provider";
import WagmiProvider from "@/providers/wagmi-provider";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "CryptoBlend",
  description: "Generated by create next app",
  icons: {
    icon: "/image/Layer_1.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <WagmiProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
            <Footer />
            <DialogLayout />
            <DrawerLayout />
            <Toaster />
          </ThemeProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
