/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Admin } from "./Admin";
export type { Campaign } from "./Campaign";
export type { CryptoCoffMember } from "./CryptoCoffMember";
export type { CryptoCoffPoint } from "./CryptoCoffPoint";
export type { MemberEmitLog } from "./MemberEmitLog";
